-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2014.4
-- Copyright (C) 2014 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rand_top_tempering is
port (
    x : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of rand_top_tempering is 
    constant ap_true : BOOLEAN := true;
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal tmp_fu_73_p4 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_4_fu_83_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal y_fu_87_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_fu_93_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_101_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_9_fu_111_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_fu_119_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_127_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_11_fu_137_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_145_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_153_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_13_fu_163_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_167_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal y_1_fu_207_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_213_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_14_fu_223_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_15_fu_233_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_5_fu_243_p7 : STD_LOGIC_VECTOR (31 downto 0);
    signal y_2_fu_259_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_fu_265_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_16_fu_275_p1 : STD_LOGIC_VECTOR (31 downto 0);


begin



    ap_return <= (tmp_16_fu_275_p1 xor y_2_fu_259_p2);
    tmp_10_fu_119_p3 <= y_fu_87_p2(14 downto 14);
    tmp_11_fu_137_p3 <= y_fu_87_p2(7 downto 7);
    tmp_12_fu_145_p3 <= y_fu_87_p2(5 downto 5);
    tmp_13_fu_163_p1 <= y_fu_87_p2(1 - 1 downto 0);
    tmp_14_fu_223_p4 <= y_1_fu_207_p2(12 downto 7);
    tmp_15_fu_233_p4 <= y_1_fu_207_p2(3 downto 2);
    tmp_16_fu_275_p1 <= std_logic_vector(resize(unsigned(tmp_6_fu_265_p4),32));
    tmp_1_fu_153_p4 <= y_fu_87_p2(3 downto 2);
    tmp_2_fu_213_p4 <= y_1_fu_207_p2(16 downto 14);
    tmp_3_fu_167_p19 <= (((((((((((((((((tmp_7_fu_93_p3 & ap_const_lv2_0) & tmp_8_fu_101_p4) & ap_const_lv1_0) & tmp_9_fu_111_p3) & ap_const_lv2_0) & tmp_10_fu_119_p3) & ap_const_lv1_0) & tmp_s_fu_127_p4) & ap_const_lv3_0) & tmp_11_fu_137_p3) & ap_const_lv1_0) & tmp_12_fu_145_p3) & ap_const_lv1_0) & tmp_1_fu_153_p4) & ap_const_lv1_0) & tmp_13_fu_163_p1) & ap_const_lv7_0);
    tmp_4_fu_83_p1 <= std_logic_vector(resize(unsigned(tmp_fu_73_p4),32));
    tmp_5_fu_243_p7 <= (((((tmp_2_fu_213_p4 & ap_const_lv1_0) & tmp_14_fu_223_p4) & ap_const_lv3_0) & tmp_15_fu_233_p4) & ap_const_lv17_0);
    tmp_6_fu_265_p4 <= y_2_fu_259_p2(31 downto 18);
    tmp_7_fu_93_p3 <= y_fu_87_p2(24 downto 24);
    tmp_8_fu_101_p4 <= y_fu_87_p2(21 downto 19);
    tmp_9_fu_111_p3 <= y_fu_87_p2(17 downto 17);
    tmp_fu_73_p4 <= x(31 downto 11);
    tmp_s_fu_127_p4 <= y_fu_87_p2(12 downto 11);
    y_1_fu_207_p2 <= (tmp_3_fu_167_p19 xor y_fu_87_p2);
    y_2_fu_259_p2 <= (tmp_5_fu_243_p7 xor y_1_fu_207_p2);
    y_fu_87_p2 <= (tmp_4_fu_83_p1 xor x);
end behav;
