-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2014.4
-- Copyright (C) 2014 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rand_top_ex_gen_uni_num is
port (
    A_read : IN STD_LOGIC_VECTOR (31 downto 0);
    B : IN STD_LOGIC_VECTOR (31 downto 0);
    C : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of rand_top_ex_gen_uni_num is 
    constant ap_true : BOOLEAN := true;
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_9908B0DF : STD_LOGIC_VECTOR (31 downto 0) := "10011001000010001011000011011111";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal tmp_fu_47_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_55_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_1_fu_65_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_4_fu_77_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_73_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp1_fu_89_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mag01_load_phi_fu_81_p3 : STD_LOGIC_VECTOR (31 downto 0);


begin



    ap_return <= (tmp1_fu_89_p2 xor mag01_load_phi_fu_81_p3);
    mag01_load_phi_fu_81_p3 <= 
        ap_const_lv32_9908B0DF when (tmp_4_fu_77_p1(0) = '1') else 
        ap_const_lv32_0;
    tmp1_fu_89_p2 <= (tmp_3_fu_73_p1 xor C);
    tmp_1_fu_65_p3 <= (tmp_fu_47_p3 & tmp_2_fu_55_p4);
    tmp_2_fu_55_p4 <= B(30 downto 1);
    tmp_3_fu_73_p1 <= std_logic_vector(resize(unsigned(tmp_1_fu_65_p3),32));
    tmp_4_fu_77_p1 <= B(1 - 1 downto 0);
    tmp_fu_47_p3 <= A_read(31 downto 31);
end behav;
