// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module rand_top_ex_gen_uni_num (
        A_read,
        B,
        C,
        ap_return
);

parameter    ap_true = 1'b1;
parameter    ap_const_lv32_1F = 32'b11111;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_1E = 32'b11110;
parameter    ap_const_lv32_9908B0DF = 32'b10011001000010001011000011011111;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;

input  [31:0] A_read;
input  [31:0] B;
input  [31:0] C;
output  [31:0] ap_return;

wire   [0:0] tmp_fu_47_p3;
wire   [29:0] tmp_2_fu_55_p4;
wire   [30:0] tmp_1_fu_65_p3;
wire   [0:0] tmp_4_fu_77_p1;
wire   [31:0] tmp_3_fu_73_p1;
wire   [31:0] tmp1_fu_89_p2;
wire   [31:0] mag01_load_phi_fu_81_p3;



assign ap_return = (tmp1_fu_89_p2 ^ mag01_load_phi_fu_81_p3);
assign mag01_load_phi_fu_81_p3 = ((tmp_4_fu_77_p1)? ap_const_lv32_9908B0DF: ap_const_lv32_0);
assign tmp1_fu_89_p2 = (tmp_3_fu_73_p1 ^ C);
assign tmp_1_fu_65_p3 = {{tmp_fu_47_p3}, {tmp_2_fu_55_p4}};
assign tmp_2_fu_55_p4 = {{B[ap_const_lv32_1E : ap_const_lv32_1]}};
assign tmp_3_fu_73_p1 = tmp_1_fu_65_p3;
assign tmp_4_fu_77_p1 = B[0:0];
assign tmp_fu_47_p3 = A_read[ap_const_lv32_1F];


endmodule //rand_top_ex_gen_uni_num

