// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module rand_top_tempering (
        x,
        ap_return
);

parameter    ap_true = 1'b1;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_1F = 32'b11111;
parameter    ap_const_lv32_18 = 32'b11000;
parameter    ap_const_lv32_13 = 32'b10011;
parameter    ap_const_lv32_15 = 32'b10101;
parameter    ap_const_lv32_11 = 32'b10001;
parameter    ap_const_lv32_E = 32'b1110;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv7_0 = 7'b0000000;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv17_0 = 17'b00000000000000000;
parameter    ap_const_lv32_12 = 32'b10010;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;

input  [31:0] x;
output  [31:0] ap_return;

wire   [20:0] tmp_fu_73_p4;
wire   [31:0] tmp_4_fu_83_p1;
wire   [31:0] y_fu_87_p2;
wire   [0:0] tmp_7_fu_93_p3;
wire   [2:0] tmp_8_fu_101_p4;
wire   [0:0] tmp_9_fu_111_p3;
wire   [0:0] tmp_10_fu_119_p3;
wire   [1:0] tmp_s_fu_127_p4;
wire   [0:0] tmp_11_fu_137_p3;
wire   [0:0] tmp_12_fu_145_p3;
wire   [1:0] tmp_1_fu_153_p4;
wire   [0:0] tmp_13_fu_163_p1;
wire   [31:0] tmp_3_fu_167_p19;
wire   [31:0] y_1_fu_207_p2;
wire   [2:0] tmp_2_fu_213_p4;
wire   [5:0] tmp_14_fu_223_p4;
wire   [1:0] tmp_15_fu_233_p4;
wire   [31:0] tmp_5_fu_243_p7;
wire   [31:0] y_2_fu_259_p2;
wire   [13:0] tmp_6_fu_265_p4;
wire   [31:0] tmp_16_fu_275_p1;



assign ap_return = (tmp_16_fu_275_p1 ^ y_2_fu_259_p2);
assign tmp_10_fu_119_p3 = y_fu_87_p2[ap_const_lv32_E];
assign tmp_11_fu_137_p3 = y_fu_87_p2[ap_const_lv32_7];
assign tmp_12_fu_145_p3 = y_fu_87_p2[ap_const_lv32_5];
assign tmp_13_fu_163_p1 = y_fu_87_p2[0:0];
assign tmp_14_fu_223_p4 = {{y_1_fu_207_p2[ap_const_lv32_C : ap_const_lv32_7]}};
assign tmp_15_fu_233_p4 = {{y_1_fu_207_p2[ap_const_lv32_3 : ap_const_lv32_2]}};
assign tmp_16_fu_275_p1 = tmp_6_fu_265_p4;
assign tmp_1_fu_153_p4 = {{y_fu_87_p2[ap_const_lv32_3 : ap_const_lv32_2]}};
assign tmp_2_fu_213_p4 = {{y_1_fu_207_p2[ap_const_lv32_10 : ap_const_lv32_E]}};
assign tmp_3_fu_167_p19 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_7_fu_93_p3}, {ap_const_lv2_0}}}, {tmp_8_fu_101_p4}}}, {ap_const_lv1_0}}}, {tmp_9_fu_111_p3}}}, {ap_const_lv2_0}}}, {tmp_10_fu_119_p3}}}, {ap_const_lv1_0}}}, {tmp_s_fu_127_p4}}}, {ap_const_lv3_0}}}, {tmp_11_fu_137_p3}}}, {ap_const_lv1_0}}}, {tmp_12_fu_145_p3}}}, {ap_const_lv1_0}}}, {tmp_1_fu_153_p4}}}, {ap_const_lv1_0}}}, {tmp_13_fu_163_p1}}}, {ap_const_lv7_0}};
assign tmp_4_fu_83_p1 = tmp_fu_73_p4;
assign tmp_5_fu_243_p7 = {{{{{{{{{{tmp_2_fu_213_p4}, {ap_const_lv1_0}}}, {tmp_14_fu_223_p4}}}, {ap_const_lv3_0}}}, {tmp_15_fu_233_p4}}}, {ap_const_lv17_0}};
assign tmp_6_fu_265_p4 = {{y_2_fu_259_p2[ap_const_lv32_1F : ap_const_lv32_12]}};
assign tmp_7_fu_93_p3 = y_fu_87_p2[ap_const_lv32_18];
assign tmp_8_fu_101_p4 = {{y_fu_87_p2[ap_const_lv32_15 : ap_const_lv32_13]}};
assign tmp_9_fu_111_p3 = y_fu_87_p2[ap_const_lv32_11];
assign tmp_fu_73_p4 = {{x[ap_const_lv32_1F : ap_const_lv32_B]}};
assign tmp_s_fu_127_p4 = {{y_fu_87_p2[ap_const_lv32_C : ap_const_lv32_B]}};
assign y_1_fu_207_p2 = (tmp_3_fu_167_p19 ^ y_fu_87_p2);
assign y_2_fu_259_p2 = (tmp_5_fu_243_p7 ^ y_1_fu_207_p2);
assign y_fu_87_p2 = (tmp_4_fu_83_p1 ^ x);


endmodule //rand_top_tempering

